# Data Modeling

In [1]:
#Import Lib
import pandas as pd

In [8]:
#Load the preprocessed data
df_data=pd.read_csv("Preprocessed_data.csv")

In [9]:
df_data.head()

,FIPSStateNumericCode,FIPSCountyCode,CoreBasedStatisticalAreaCode,CensusTractIdentifier,CensusTractMinorityRatioPercent,CensusTractMedFamIncomeAmount,LocalAreaMedianIncomeAmount,TotalMonthlyIncomeAmount,HUDMedianIncomeAmount,LoanAcquisitionActualUPBAmt,...,PT11,PT12,1.12,2.8,3.6,4.4,1.13,2.9,3.7,1.14
0,50,7,15540,34.0,4.577,132474.0,84290.0,7308,93000,319113,...,0,0,0,1,0,0,0,1,0,1
1,50,7,15540,29.0,3.421,100795.0,84290.0,7416,93000,248005,...,0,0,0,1,0,0,0,1,0,1
2,50,15,99999,9532.0,6.152,49625.0,67566.0,5143,71900,211105,...,0,0,0,1,0,0,0,1,0,1
3,50,17,30100,9594.0,3.935,62643.0,67105.0,8866,71900,210000,...,0,0,0,1,0,0,0,1,0,1
4,23,31,38860,254.0,6.031,87679.0,76445.0,15240,90100,233200,...,0,0,0,1,0,0,0,1,0,1

In [10]:
df_data.shape

(82415, 102)

# Train Test Split

In [11]:
y=df_data["Borrower1Race1Type"]
X=df_data.loc[:, df_data.columns != 'Borrower1Race1Type']
X.head()
list(X.columns)

['FIPSStateNumericCode',
 'FIPSCountyCode',
 'CoreBasedStatisticalAreaCode',
 'CensusTractIdentifier',
 'CensusTractMinorityRatioPercent',
 'CensusTractMedFamIncomeAmount',
 'LocalAreaMedianIncomeAmount',
 'TotalMonthlyIncomeAmount',
 'HUDMedianIncomeAmount',
 'LoanAcquisitionActualUPBAmt',
 'LTVRatioPercent',
 'ScheduledTotalPaymentCount',
 'Borrower1AgeAtApplicationYears',
 'Borrower2AgeAtApplicationYears',
 'PropertyUnitCount',
 'NoteRatePercent',
 'NoteAmount',
 'HousingExpenseRatioPercent',
 'TotalDebtExpenseRatioPercent',
 'PMICoveragePercent',
 'TotalYearlyIncomeAmount',
 'Diff_median_yearly_income',
 'Boston',
 'Chicago',
 'Cincinnati',
 'Dallas',
 'Des Moines',
 'Indianapolis',
 'New York',
 'Pittsburgh',
 'San Francisco',
 'Topeka',
 '2014',
 '2015',
 '2016',
 '2017',
 '2018',
 '2019',
 '2019.1',
 '1',
 '2',
 '6',
 '1.1',
 '0',
 '1.2',
 '2.1',
 '3',
 '1.3',
 '9',
 '1.4',
 '2.2',
 '3.1',
 '4',
 '5',
 '0.1',
 '1.5',
 '1.6',
 '2.3',
 '3.2',
 '6.1',
 '1.7',
 '2.4',
 '3.3',
 '4.1',
 '6.2',
 '1.8',
 '2.5',
 '1.9',
 '2.6',
 '3.4',
 '4.2',
 '5.1',
 '9.1',
 '1.10',
 '2.7',
 '3.5',
 '4.3',
 '5.2',
 '9.2',
 '0.2',
 '1.11',
 'PT01',
 'PT02',
 'PT03',
 'PT04',
 'PT05',
 'PT06',
 'PT07',
 'PT08',
 'PT09',
 'PT10',
 'PT11',
 'PT12',
 '1.12',
 '2.8',
 '3.6',
 '4.4',
 '1.13',
 '2.9',
 '3.7',
 '1.14']